#!/bin/sh
##############################################################################
# (c) SZABO Gergely, 2009
# Free software, distributed under the GNU GPL license
# There is absolutely no warranty.
##############################################################################
QUERY=""
for WORD in "$@"; do
  QUERY="${QUERY}${WORD}+";
done
URL="http://www.google.com/search?q=${QUERY}"
gnome-open $URL
