.TH TAPETA 1 "Distributed under GNU GPL" "(c) SZABO Gergely"
.SH NAME
tapeta \- Wallpaper slideshow
.SH SYNOPSIS
.B tapeta
[
.B -h
]
.SH DESCRIPTION
.B Tapeta
is a trivially simple destop wallpaper slideshow program for the
.B Gnome2
or
.B MATE
desktop environment.
.PP
Tipically, use tapeta as a Startup Application in Gnome/Mate.
.SH FILES
Config file
.BR ~/.tapeta
is read for cycle period [s] and the folder with the wallpaper pictures.
The config file is read periodically, so settings can be altered on the fly.
.PP
A default config file is created first time with a cycle time of 10 min
and ~/Pictures as the default folder.
.SH SEE ALSO
.BR "gconftool-2" "    Configuration tool for the Gnome2 desktop environment"
.br
.BR "mateconftool-2" " Configuration tool for the MATE desktop environment"
.SH AUTHOR
SZABO Gergely
.B szg@subogero.com
.br
Homepage:
.B http://linux.subogero.com/go
.SH COPYRIGHT
This is Free software, distributed under the GNU GPL license.
.br
There is absolutely no warranty.
.SH BUG REPORTS
Please report bugs to the above address.
.br
Please include
.B tapeta
in the Subject field.
