#!/bin/sh
##############################################################################
# (c) SZABO Gergely, 2012
# Free software, distributed under the WTFPL license
##############################################################################
if [ "$1" = -h ]; then
cat <<EOF
Usage: tapeta [ CMD | -h ]
-h	show this help text
CMD	commands start / stop / reload

Tipically, use tapeta as a Startup Application in Gnome/Mate.

Config file ~/.tapeta is read for cycle period [s] and the folder
with the wallpaper pictures to cycle.
The config file is read periodically, so settings can be altered on the fly.

A default config file is created first time with a cycle time of 10 min
and ~/Pictures as the default folder.
EOF
exit 0
fi

case "$1" in
start)
  [ -f ~/.tapeta.pid ] || nohup tapeta >/dev/null 2>&1 &
  exit 0
  ;;
reload)
  kill `cat ~/.tapeta.pid`
  nohup tapeta >/dev/null 2>&1 &
  exit 0
  ;;
stop)
  kill `cat ~/.tapeta.pid`
  rm ~/.tapeta.pid
  exit 0
  ;;
esac

echo $$ > ~/.tapeta.pid

# Create default cnfig file if necessary
if [ ! -f ~/.tapeta ]; then
  echo t=600 > ~/.tapeta
  echo dir=/home/$USER/Pictures >> ~/.tapeta
  echo ordered=no >> ~/.tapeta
fi

# Cycle through pictures
while true; do
  SLEEP=`sed -rn 's/^t=([0-9]+)$/\1/p' ~/.tapeta`
  [ "$SLEEP" = 0 ] && exit 0
  sleep $SLEEP || exit 1
  ACONLY=`sed -rn 's/^AConly=(.+)$/\1/p' ~/.tapeta`
  if [ "$ACONLY" = yes ]; then
     upower -i `upower -e | grep AC`| grep 'online: *yes' >/dev/null || continue
  fi
  DIR=`sed -rn 's/^dir=(.+)$/\1/p' ~/.tapeta`
  ORDER=`sed -rn 's/^ordered=(.+)$/\1/p' ~/.tapeta`
  if [ "$ORDER" = yes ]; then
    unset FIRST
    unset LAST
    for i in `ls -1 --file-type "$DIR" | grep '[^/]$'`; do
      [ -z "$FIRST" ] && FIRST="$i"
      [ "$LAST" ] && FILE="$i" && break
      [ "$FILE" = "$i" ] && LAST="$i"
    done
    [ "$FILE" = "$LAST" -o -z "$LAST" ] && FILE=$FIRST
  else
    FILE=`ls -1 --file-type "$DIR" | grep '[^/]$' | shuf -n1`
  fi
  [ -z "$FILE" ] && continue
  if ps -A | grep '\bmdm\b' >/dev/null; then
    gsettings set org.mate.background picture-filename "$DIR/$FILE"
  else
    gconftool-2 -t string -s /desktop/gnome/background/picture_filename "$DIR/$FILE"
  fi
done
